In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'creditcardfraud' dataset.
Path to dataset files: /kaggle/input/creditcardfraud

In [ ]:
import os
os.makedirs("data",exist_ok=True)

In [ ]:
!mv /kaggle/input/creditcardfraud/* /content/data

mv: cannot remove '/kaggle/input/creditcardfraud/creditcard.csv': Read-only file system

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
data = pd.read_csv("/content/data/creditcard.csv")
data = data.sample(5000)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data.drop("Class", axis=1), data["Class"], test_size=0.2, random_state=32)

In [ ]:
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [ ]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.998
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       998
           1       0.50      0.50      0.50         2

    accuracy                           1.00      1000
   macro avg       0.75      0.75      0.75      1000
weighted avg       1.00      1.00      1.00      1000

# **TECHNIQUES**

1) Undersampling

In [ ]:
from imblearn.under_sampling import RandomUnderSampler

In [ ]:
data = pd.read_csv("/content/data/creditcard.csv")
data.shape

(284807, 31)

In [ ]:
data["Class"].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [ ]:
X = data.drop("Class", axis=1)
y = data["Class"]

In [ ]:
X_sampled, y_sampled = RandomUnderSampler(random_state=32).fit_resample(X, y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_sampled, y_sampled, test_size=0.2, random_state=32)

In [ ]:
model = LogisticRegression()
model.fit(X_sampled, y_sampled)
y_pred = model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9543147208121827
              precision    recall  f1-score   support

           0       0.95      0.96      0.96       102
           1       0.96      0.95      0.95        95

    accuracy                           0.95       197
   macro avg       0.95      0.95      0.95       197
weighted avg       0.95      0.95      0.95       197

In [ ]:
X_sampled.shape

(984, 30)

In [ ]:
y_sampled.value_counts()

Class
0    492
1    492
Name: count, dtype: int64

2) Oversampling

In [ ]:
from imblearn.over_sampling import RandomOverSampler

In [ ]:
data = pd.read_csv("/content/data/creditcard.csv")
data.shape
data = data.sample(30000)

In [ ]:
data["Class"].value_counts()

Class
0    29945
1       55
Name: count, dtype: int64

In [ ]:
X = data.drop("Class", axis=1)
y = data["Class"]

In [ ]:
X_sampled, y_sampled = RandomOverSampler(random_state=32).fit_resample(X, y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_sampled, y_sampled, test_size=0.2, random_state=32)

In [ ]:
model = LogisticRegression()
model.fit(X_sampled, y_sampled)
y_pred = model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9615127734179328
              precision    recall  f1-score   support

           0       0.96      0.96      0.96      5977
           1       0.96      0.96      0.96      6001

    accuracy                           0.96     11978
   macro avg       0.96      0.96      0.96     11978
weighted avg       0.96      0.96      0.96     11978

In [ ]:
X_sampled.shape

(59890, 30)

In [ ]:
y_sampled.value_counts()

Class
0    29945
1    29945
Name: count, dtype: int64

3) SMOTE - Synthetic Minority Oversampling Technique

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
data = pd.read_csv("/content/data/creditcard.csv")
data.shape

(284807, 31)

In [ ]:
data["Class"].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [ ]:
X = data.drop("Class", axis=1)
y = data["Class"]

In [ ]:
X_sampled, y_sampled = SMOTE(random_state=32).fit_resample(X, y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_sampled, y_sampled, test_size=0.2, random_state=32)

In [ ]:
model = LogisticRegression()
model.fit(X_sampled, y_sampled)
y_pred = model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9729085697202047
              precision    recall  f1-score   support

           0       0.97      0.98      0.97     56743
           1       0.98      0.97      0.97     56983

    accuracy                           0.97    113726
   macro avg       0.97      0.97      0.97    113726
weighted avg       0.97      0.97      0.97    113726

In [ ]:
X_sampled.shape

(568630, 30)

In [ ]:
y_sampled.value_counts()

Class
0    284315
1    284315
Name: count, dtype: int64

4) Class weights

In [ ]:
data = pd.read_csv("/content/data/creditcard.csv")
data.shape

(284807, 31)

In [ ]:
data["Class"].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [ ]:
X = data.drop("Class", axis=1)
y = data["Class"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=32)

In [ ]:
model = LogisticRegression(class_weight={0:1, 1:5}, solver='liblinear')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [ ]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9992451107756047
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56850
           1       0.82      0.79      0.81       112

    accuracy                           1.00     56962
   macro avg       0.91      0.90      0.90     56962
weighted avg       1.00      1.00      1.00     56962