### What is Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

https://pandas.pydata.org/about/index.html

### Pandas Series

A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

In [1]:
import numpy as np
import pandas as pd

### 1) Creating Series

In [2]:
# Series from list of integers
series1 = pd.Series([1,2,3,4,5,6])
print(series1)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
# Series from list of strings
series2 = pd.Series(["Apples", "Oranges", "Kiwi", "Bananas"])
print(series2)

0     Apples
1    Oranges
2       Kiwi
3    Bananas
dtype: object

In [4]:
# Custom indices and names
marks = [10,20,30,40,50]
students = ["A", "B", "C", "D", "E"]
series3 = pd.Series(marks, index=students, name="Student marks")
print(series3)

A    10
B    20
C    30
D    40
E    50
Name: Student marks, dtype: int64

In [5]:
# Series from dictionary
marks = {
    "A": 10,
    "B":20,
    "C":30,
    "D":40,
    "E":50,
}
series = pd.Series(marks)
print(series)

A    10
B    20
C    30
D    40
E    50
dtype: int64

### 2) Series Attributes

In [6]:
marks = {
    "A": 10,
    "B":20,
    "C":30,
    "D":40,
    "E":50,
}
series = pd.Series(marks, name="Marks of Students")
print(series)

series1 = pd.Series([1,2,3,4,5,6])
series2 = pd.Series([1,2,2,4,2,6])
print("\n")
print(series1)
print("\n")
print(series2)

A    10
B    20
C    30
D    40
E    50
Name: Marks of Students, dtype: int64


0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


0    1
1    2
2    2
3    4
4    2
5    6
dtype: int64

In [7]:
# .size : no of elements in series
print(series.size)

5

In [8]:
# .dtype : dtype of elements in series
print(series.dtype)

int64

In [9]:
# .name : name of series
print(series.name)

Marks of Students

In [10]:
# is_unique :  returns true or False whether or not all values are unique
print(series1.is_unique)
print(series2.is_unique)

True
False

In [11]:
# .index : Returns indices of series
print(series.index)
print(series1.index)

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
RangeIndex(start=0, stop=6, step=1)

In [12]:
# .values : Returns values of series
print(series.values)
print(series1.values)

[10 20 30 40 50]
[1 2 3 4 5 6]

### 3) Series Methods

In [13]:
series = pd.Series(np.random.randint(1,100,30))
print(series)

0     84
1     86
2     72
3     54
4     44
5     24
6     76
7     14
8     50
9     58
10    21
11    79
12    21
13    86
14    95
15    21
16     3
17    73
18    77
19     4
20    34
21    74
22    80
23    32
24    62
25    78
26     5
27    16
28    53
29    62
dtype: int64

In [14]:
# head() and tail() : head(n) -> top n rows, tail(n) -> bottom n rows
# if n is not passed, by default, 5 rows are returned
print(series.head())
print("\n")
print(series.head(10))
print("\n")
print(series.tail())
print("\n")
print(series.tail(10))
print("\n")

0    84
1    86
2    72
3    54
4    44
dtype: int64


0    84
1    86
2    72
3    54
4    44
5    24
6    76
7    14
8    50
9    58
dtype: int64


25    78
26     5
27    16
28    53
29    62
dtype: int64


20    34
21    74
22    80
23    32
24    62
25    78
26     5
27    16
28    53
29    62
dtype: int64

In [15]:
# sample(n) -> return random n rows
# if n is not passed, by default, 1 row are returned
print(series.sample())
print("\n")
print(series.sample(10))
print("\n")

15    21
dtype: int64


18    77
27    16
28    53
19     4
23    32
1     86
12    21
26     5
25    78
24    62
dtype: int64

In [16]:
# value_counts() -> returns number of occurances of each value
print(series.value_counts())

21    3
86    2
62    2
54    1
72    1
24    1
76    1
14    1
44    1
84    1
58    1
50    1
95    1
79    1
73    1
77    1
4     1
3     1
34    1
74    1
80    1
32    1
78    1
5     1
16    1
53    1
Name: count, dtype: int64

In [17]:
# sort_values() -> sorts series

# Ascending order
print(series.sort_values())
print("\n\n")
# Descending order
print(series.sort_values(ascending=False))

16     3
19     4
26     5
7     14
27    16
15    21
12    21
10    21
5     24
23    32
20    34
4     44
8     50
28    53
3     54
9     58
29    62
24    62
2     72
17    73
21    74
6     76
18    77
25    78
11    79
22    80
0     84
1     86
13    86
14    95
dtype: int64



14    95
1     86
13    86
0     84
22    80
11    79
25    78
18    77
6     76
21    74
17    73
2     72
24    62
29    62
9     58
3     54
28    53
8     50
4     44
20    34
23    32
5     24
10    21
12    21
15    21
27    16
7     14
26     5
19     4
16     3
dtype: int64

In [18]:
# inplace parameter : Modifies original series
series.sort_values(inplace=True)
print(series)

16     3
19     4
26     5
7     14
27    16
15    21
12    21
10    21
5     24
23    32
20    34
4     44
8     50
28    53
3     54
9     58
29    62
24    62
2     72
17    73
21    74
6     76
18    77
25    78
11    79
22    80
0     84
1     86
13    86
14    95
dtype: int64

In [19]:
# sort_index() : sorts indices
# parameters: ascending = True/False , inplace = True/False
series.sort_index(inplace=True)
print(series)

0     84
1     86
2     72
3     54
4     44
5     24
6     76
7     14
8     50
9     58
10    21
11    79
12    21
13    86
14    95
15    21
16     3
17    73
18    77
19     4
20    34
21    74
22    80
23    32
24    62
25    78
26     5
27    16
28    53
29    62
dtype: int64

### 4) Series Math Methods

In [20]:
series = pd.Series(np.random.randint(1,100,10))
print(series)

0    97
1    94
2    11
3    17
4    63
5     2
6    71
7    30
8    99
9    61
dtype: int64

In [21]:
# count : returns number of elements in series
# similar to size but in size, it includes missing values
# but count doesnt

series1 = pd.Series([1,2,4,3,np.nan,8,9,11])

print(series1.count())
print(series1.size)

7
8

In [22]:
# sum() and product() : sum and product of all values
print(series.sum())
print(series.product())

545
2763480297390120

In [23]:
# min() and max()
print(series.max())
print(series.min())

99
2

In [24]:
# statistical methods

print(series.mean())
print(series.median())
print(series.mode())
print(series.std())
print(series.var())

54.5
62.0
0     2
1    11
2    17
3    30
4    61
5    63
6    71
7    94
8    97
9    99
dtype: int64
37.1012129181783
1376.5

In [25]:
# describe() : gives summary of all mathematical functions
print(series.describe())

count    10.000000
mean     54.500000
std      37.101213
min       2.000000
25%      20.250000
50%      62.000000
75%      88.250000
max      99.000000
dtype: float64

### 5) Series Indexing and Slicing

In [26]:
series1 = pd.Series(np.random.randint(1,100,20))
print(series1)

print("\n\n")

series2 = pd.Series(["Apple","Banana","Grape","Plum","Orange","Kiwi","Guava","Watermelon"])
print(series2)

0     66
1     28
2     60
3     91
4     71
5     99
6     98
7      4
8     77
9     22
10    45
11    77
12    50
13    88
14    39
15    68
16    16
17     6
18    87
19    41
dtype: int64



0         Apple
1        Banana
2         Grape
3          Plum
4        Orange
5          Kiwi
6         Guava
7    Watermelon
dtype: object

In [27]:
# Integer indexing
print(series1[0])
print(series2[5])

66
Kiwi

In [28]:
# Slicing
print(series1[0:5])
print("\n")

print(series1[-5:])
print("\n")

print(series1[2::2])
print("\n")

print(series2[0:5])
print("\n")

print(series2[-5:])
print("\n")

0    66
1    28
2    60
3    91
4    71
dtype: int64


15    68
16    16
17     6
18    87
19    41
dtype: int64


2     60
4     71
6     98
8     77
10    45
12    50
14    39
16    16
18    87
dtype: int64


0     Apple
1    Banana
2     Grape
3      Plum
4    Orange
dtype: object


3          Plum
4        Orange
5          Kiwi
6         Guava
7    Watermelon
dtype: object

In [29]:
# Fancy Indexing
print(series1[[1,4,6,9,12]])
print("\n")
print(series2[[1,4,6]])

1     28
4     71
6     98
9     22
12    50
dtype: int64


1    Banana
4    Orange
6     Guava
dtype: object

In [30]:
# Boolean Indexing
print(series1[series1>50])

0     66
2     60
3     91
4     71
5     99
6     98
8     77
11    77
13    88
15    68
18    87
dtype: int64

### 6) Excess Functions Series

In [31]:
series = pd.Series([1,1,0,0,1,1,0,1])
series

0    1
1    1
2    0
3    0
4    1
5    1
6    0
7    1
dtype: int64

In [32]:
# astype: changes datatype of series
series = series.astype(bool)
series

0     True
1     True
2    False
3    False
4     True
5     True
6    False
7     True
dtype: bool

In [33]:
# drop_duplicates: removes duplicates from series
series = pd.Series([1,2,3,1,1,3,4,1,3,5,6,1,4,5,9])
series.drop_duplicates()

0     1
1     2
2     3
6     4
9     5
10    6
14    9
dtype: int64

In [34]:
# duplicated: creates a series of bools
# Can be used to find how many duplicates in series
series = pd.Series([1,2,3,1,1,3,4,1,3,5,6,1,4,5,9])
series.duplicated().sum()

np.int64(8)

In [35]:
# isnull : creates a series of bools
# Can be used to find how many nulls in series
series = pd.Series([1,4,np.nan,5,np.nan,1,9,3,np.nan])
series.isna().sum()

np.int64(3)

In [36]:
# dropna : deletes all missing values
print(series)
print("\n")
temp = series.dropna()
print(temp)

0    1.0
1    4.0
2    NaN
3    5.0
4    NaN
5    1.0
6    9.0
7    3.0
8    NaN
dtype: float64


0    1.0
1    4.0
3    5.0
5    1.0
6    9.0
7    3.0
dtype: float64

In [37]:
# fillna : fills all missing values with given values
print(series)
print("\n")
temp = series.fillna("Missing")
print(temp)

0    1.0
1    4.0
2    NaN
3    5.0
4    NaN
5    1.0
6    9.0
7    3.0
8    NaN
dtype: float64


0        1.0
1        4.0
2    Missing
3        5.0
4    Missing
5        1.0
6        9.0
7        3.0
8    Missing
dtype: object

In [38]:
# apply : allows using functions on each row of series
def add(s):
  return s+10

series = pd.Series([1,2,3,4,5,6,7])
print(series.apply(add))

0    11
1    12
2    13
3    14
4    15
5    16
6    17
dtype: int64

# **DataFrame**

In [39]:
# DF from Lists
student_data = [
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,50,2]
]

df = pd.DataFrame(student_data, columns = ["iq","marks","package"])
print(df)

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [40]:
# DF from dictionary
student_dict = {
    'name': ['nitish','ankit','rupesh','rishabh','amit','ankita'],
    'iq': [100,90,120,80,0,0],
    'marks': [80,70,100,50,0,0],
    'package': [10,7,14,2,0,0]
}

df = pd.DataFrame(student_dict)
print(df)

      name   iq  marks  package
0   nitish  100     80       10
1    ankit   90     70        7
2   rupesh  120    100       14
3  rishabh   80     50        2
4     amit    0      0        0
5   ankita    0      0        0

In [41]:
# From CSV
df = pd.read_csv("/content/batsman_runs.csv")
print(df)

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

### 1) DF methods

In [42]:
movies = pd.read_csv("/content/movies.csv")
ipl = pd.read_csv("/content/ipl-matches.csv")
batsman = pd.read_csv("/content/batsman_runs.csv")

In [43]:
# shape
print(movies.shape)
print(ipl.shape)

(1629, 18)
(950, 20)

In [44]:
# dtypes
print(movies.dtypes)
print("\n")
print(ipl.dtypes)

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object


ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [45]:
# index
print(movies.index)
print(ipl.index)

RangeIndex(start=0, stop=1629, step=1)
RangeIndex(start=0, stop=950, step=1)

In [46]:
# columns
print(movies.columns)
print(ipl.columns)
print(batsman.columns)

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')
Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')
Index(['batter', 'batsman_run'], dtype='object')

In [47]:
# values
print(batsman.values)

[['A Ashish Reddy' 280]
 ['A Badoni' 161]
 ['A Chandila' 4]
 ...
 ['Younis Khan' 3]
 ['Yuvraj Singh' 2754]
 ['Z Khan' 117]]

In [48]:
# head and tail
print(movies.head(2))

                    title_x    imdb_id  \
0  Uri: The Surgical Strike  tt8291224
1             Battalion 609  tt9472208

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...
1                                                NaN

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1        https://en.wikipedia.org/wiki/Battalion_609

                    title_y            original_title  is_adult  \
0  Uri: The Surgical Strike  Uri: The Surgical Strike         0
1             Battalion 609             Battalion 609         0

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112
1             2019     131               War          4.1          73

                                               story  \
0  Divided over five chapters  the film chronicle...
1  The story revolves around a cricket match betw...

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN
1  The story of Battalion 609 revolves around a c...     NaN

                                              actors wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...           4 wins
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...              NaN

              release_date
0    11 January 2019 (USA)
1  11 January 2019 (India)

In [49]:
print(ipl.tail(2))

         ID        City        Date   Season MatchNumber  \
948  335983  Chandigarh  2008-04-19  2007/08           2
949  335982   Bangalore  2008-04-18  2007/08           1

                           Team1                  Team2  \
948              Kings XI Punjab    Chennai Super Kings
949  Royal Challengers Bangalore  Kolkata Knight Riders

                                          Venue                   TossWinner  \
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore

    TossDecision SuperOver            WinningTeam WonBy  Margin method  \
948          bat         N    Chennai Super Kings  Runs    33.0    NaN
949        field         N  Kolkata Knight Riders  Runs   140.0    NaN

    Player_of_Match                                       Team1Players  \
948      MEK Hussey  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...
949     BB McCullum  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...

                                          Team2Players    Umpire1      Umpire2
948  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...  MR Benson   SL Shastri
949  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...  Asad Rauf  RE Koertzen

In [50]:
# sample
print(ipl.sample(5))

          ID     City        Date   Season MatchNumber  \
432   980901   Mumbai  2016-04-09     2016           1
217  1178412    Delhi  2019-04-20     2019          37
147  1216524      NaN  2020-10-27  2020/21          47
417   980931     Pune  2016-04-22     2016          16
121  1254070  Chennai  2021-04-20     2021          13

                       Team1                        Team2  \
432           Mumbai Indians      Rising Pune Supergiants
217          Kings XI Punjab               Delhi Capitals
147      Sunrisers Hyderabad               Delhi Capitals
417  Rising Pune Supergiants  Royal Challengers Bangalore
121           Mumbai Indians               Delhi Capitals

                                        Venue               TossWinner  \
432                          Wankhede Stadium           Mumbai Indians
217                      Arun Jaitley Stadium           Delhi Capitals
147       Dubai International Cricket Stadium           Delhi Capitals
417   Maharashtra Cricket Association Stadium  Rising Pune Supergiants
121  MA Chidambaram Stadium, Chepauk, Chennai           Mumbai Indians

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
432          bat         N      Rising Pune Supergiants  Wickets     9.0
217        field         N               Delhi Capitals  Wickets     5.0
147        field         N          Sunrisers Hyderabad     Runs    88.0
417        field         N  Royal Challengers Bangalore     Runs    13.0
121          bat         N               Delhi Capitals  Wickets     6.0

    method Player_of_Match                                       Team1Players  \
432    NaN       AM Rahane  ['LMP Simmons', 'RG Sharma', 'HH Pandya', 'JC ...
217    NaN         SS Iyer  ['KL Rahul', 'CH Gayle', 'MA Agarwal', 'DA Mil...
147    NaN         WP Saha  ['DA Warner', 'WP Saha', 'MK Pandey', 'KS Will...
417    NaN  AB de Villiers  ['AM Rahane', 'F du Plessis', 'KP Pietersen', ...
121    NaN        A Mishra  ['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...

                                          Team2Players          Umpire1  \
432  ['AM Rahane', 'F du Plessis', 'KP Pietersen', ...  HDPK Dharmasena
217  ['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...    C Shamshuddin
147  ['AM Rahane', 'S Dhawan', 'MP Stoinis', 'SO He...     AK Chaudhary
417  ['V Kohli', 'KL Rahul', 'AB de Villiers', 'SR ...      CB Gaffaney
121  ['PP Shaw', 'S Dhawan', 'SPD Smith', 'Lalit Ya...    C Shamshuddin

         Umpire2
432    CK Nandan
217    UV Gandhe
147  Nitin Menon
417    VK Sharma
121  CB Gaffaney

In [51]:
# info
print(movies.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB
None

In [52]:
# describe
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [53]:
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [54]:
# isnull
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [55]:
# duplicated
movies.duplicated().sum()

np.int64(0)

In [56]:
ipl.duplicated().sum()

np.int64(0)

In [57]:
# rename
print(batsman.head())
renamed = batsman.rename(columns={'batter':'batsman','batsman_run':'runs'})
print("\n")
print(renamed.head())

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25


          batsman  runs
0  A Ashish Reddy   280
1        A Badoni   161
2      A Chandila     4
3        A Chopra    53
4     A Choudhary    25

### 2) DF Math Methods

In [58]:
df = pd.DataFrame(np.random.randint(1,100,30).reshape(5,6))
print(df)

    0   1   2   3   4   5
0  59  80  27  17  62  37
1  45  55  31  17  65  61
2  30  27  95  79  61  87
3  98  66  98  37  75  23
4  64   6  53  40  30   6

In [59]:
# sum -> axis argument
print(df.sum(axis=0))   # column wise
print("\n")
print(df.sum(axis=1))  # row wise

0    296
1    234
2    304
3    190
4    293
5    214
dtype: int64


0    282
1    274
2    379
3    397
4    199
dtype: int64

In [60]:
df.mean()

0    59.2
1    46.8
2    60.8
3    38.0
4    58.6
5    42.8
dtype: float64

In [61]:
df.var()

0     645.7
1     898.7
2    1161.2
3     642.0
4     286.3
5    1016.2
dtype: float64

### 3) Accessing columns from DF

In [62]:
data = {
    0: [10, 20, 30],
    1: [40, 50, 60],
    2: [70, 80, 90]
}

index = ["row_A", "row_B", "row_C"]

df = pd.DataFrame(data, index=index)
print(df)

        0   1   2
row_A  10  40  70
row_B  20  50  80
row_C  30  60  90

In [63]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [24, 27, 22],
    "City": ["Delhi", "Mumbai", "Bangalore"]
}

index = ["id_101", "id_102", "id_103"]

df2 = pd.DataFrame(data, index=index)
print(df2)

           Name  Age       City
id_101    Alice   24      Delhi
id_102      Bob   27     Mumbai
id_103  Charlie   22  Bangalore

In [64]:
# Single column
print(df[0])
print("\n")
print(df2["Name"])

row_A    10
row_B    20
row_C    30
Name: 0, dtype: int64


id_101      Alice
id_102        Bob
id_103    Charlie
Name: Name, dtype: object

In [65]:
# Multiple columns by fancy indexing

print(df[[0,2]])
print("\n")
print(df2[["Name","City","Age"]])

        0   2
row_A  10  70
row_B  20  80
row_C  30  90


           Name       City  Age
id_101    Alice      Delhi   24
id_102      Bob     Mumbai   27
id_103  Charlie  Bangalore   22

### 4) Accessing rows from DF

In [66]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank"],
    "Age": [24, 27, 22, 25, 26, 28],
    "City": ["Delhi", "Mumbai", "Bangalore", "Chennai", "Pune", "Hyderabad"],
    "Salary": [50000, 60000, 55000, 58000, 62000, 65000],
    "Experience": [2, 4, 1, 3, 5, 6]
}

index = [
    "id_101",
    "id_102",
    "id_103",
    "id_104",
    "id_105",
    "id_106"
]

df = pd.DataFrame(data, index=index)
print(df)

           Name  Age       City  Salary  Experience
id_101    Alice   24      Delhi   50000           2
id_102      Bob   27     Mumbai   60000           4
id_103  Charlie   22  Bangalore   55000           1
id_104    David   25    Chennai   58000           3
id_105      Eve   26       Pune   62000           5
id_106    Frank   28  Hyderabad   65000           6

In [67]:
# iloc: Searched used index positions
print(df.iloc[0])   # Single row
print("\n")
print(df.iloc[0:5])  # Multiple rows
print("\n")
print(df.iloc[[0,4,1,3]])  # Fancy indexing

Name          Alice
Age              24
City          Delhi
Salary        50000
Experience        2
Name: id_101, dtype: object


           Name  Age       City  Salary  Experience
id_101    Alice   24      Delhi   50000           2
id_102      Bob   27     Mumbai   60000           4
id_103  Charlie   22  Bangalore   55000           1
id_104    David   25    Chennai   58000           3
id_105      Eve   26       Pune   62000           5


         Name  Age     City  Salary  Experience
id_101  Alice   24    Delhi   50000           2
id_105    Eve   26     Pune   62000           5
id_102    Bob   27   Mumbai   60000           4
id_104  David   25  Chennai   58000           3

In [68]:
# loc : Fetches rows according to index name
print(df.loc["id_101"])   # Single row
print("\n")
print(df.loc["id_101":"id_104"])  # Multiple rows
print("\n")
print(df.loc[["id_101","id_104","id_103"]])  # Fancy indexing

Name          Alice
Age              24
City          Delhi
Salary        50000
Experience        2
Name: id_101, dtype: object


           Name  Age       City  Salary  Experience
id_101    Alice   24      Delhi   50000           2
id_102      Bob   27     Mumbai   60000           4
id_103  Charlie   22  Bangalore   55000           1
id_104    David   25    Chennai   58000           3


           Name  Age       City  Salary  Experience
id_101    Alice   24      Delhi   50000           2
id_104    David   25    Chennai   58000           3
id_103  Charlie   22  Bangalore   55000           1

### 5) Accessing both cols and rows

In [69]:
df

           Name  Age       City  Salary  Experience
id_101    Alice   24      Delhi   50000           2
id_102      Bob   27     Mumbai   60000           4
id_103  Charlie   22  Bangalore   55000           1
id_104    David   25    Chennai   58000           3
id_105      Eve   26       Pune   62000           5
id_106    Frank   28  Hyderabad   65000           6

In [70]:
df.iloc[0:3,0:2]

           Name  Age
id_101    Alice   24
id_102      Bob   27
id_103  Charlie   22

### 6) Applying functions on dataframes

In [71]:
df = pd.DataFrame(np.random.randint(1,100,30).reshape(5,6))
print(df)

    0   1   2   3   4   5
0   2  45  71  74  52  32
1  32  46  33  25  83  23
2   1  12  18  15  26   8
3  67   9  47  93  75  99
4  40  33  22  19  50  53

In [72]:
def add_ten(x):
  return x+10
df = df.apply(add_ten)
df

    0   1   2    3   4    5
0  12  55  81   84  62   42
1  42  56  43   35  93   33
2  11  22  28   25  36   18
3  77  19  57  103  85  109
4  50  43  32   29  60   63

### 7) Filtering DataFrame

In [73]:
ipl.sample(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
892,336040,Mumbai,2008-06-01,2007/08,Final,Chennai Super Kings,Rajasthan Royals,Dr DY Patil Sports Academy,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,3.0,NaN,YK Pathan,"['PA Patel', 'S Vidyut', 'SK Raina', 'JA Morke...","['NK Patel', 'SA Asnodkar', 'Kamran Akmal', 'S...",BF Bowden,RE Koertzen
796,419144,Kolkata,2010-04-07,2009/10,39,Kolkata Knight Riders,Delhi Daredevils,Eden Gardens,Kolkata Knight Riders,bat,N,Kolkata Knight Riders,Runs,14.0,NaN,SC Ganguly,"['SC Ganguly', 'CH Gayle', 'BB McCullum', 'MK ...","['DA Warner', 'V Sehwag', 'G Gambhir', 'PD Col...",BG Jerling,RE Koertzen

In [74]:
# find out the final winners
ipl[ipl["MatchNumber"] == "Final"][["Season","WinningTeam"]]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [75]:
# how many super over finishes have occured
ipl[ipl["SuperOver"] == "Y"].shape[0]

14

In [76]:
# how many matches has CSK won in Kolkata
ipl[(ipl["City"] == "Kolkata") & (ipl["WinningTeam"] == "Chennai Super Kings")].shape[0]

5

In [77]:
# toss winner is match winner in percentage
num = ipl[ipl["TossWinner"] == ipl["WinningTeam"]].shape[0]
total_rows = ipl.shape[0]
percentage = (num/total_rows) * 100
print(f"Percentage: {percentage}")

Percentage: 51.473684210526315

In [78]:
movies.sample(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
242,Jia Aur Jia,tt3338188,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jia_aur_Jia,Jia aur Jia,Jia aur Jia,0,2017,93,Drama,4.6,140,A story about two starkly different women that...,A story about two starkly different women that...,Life is short,Richa Chadha|Kalki Koechlin|Arslan Goni|,NaN,27 October 2017 (India)
656,Chaalis Chauraasi,tt2184125,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chaalis_Chauraasi,Chaalis Chauraasi,Chaalis Chauraasi,0,2012,120,Comedy|Crime,6.1,444,Four friends who have accidentally committed ...,Four friends who have accidentally committed ...,One night...one hell of a ride!,Naseeruddin Shah|Kay Kay Menon|Atul Kulkarni|R...,NaN,13 January 2012 (India)

In [79]:
# movies with rating higher than 8 and votes > 10000
movies[(movies["imdb_rating"] > 8) & (movies["imdb_votes"] > 10000)][["original_title","imdb_rating","imdb_votes"]]

                         original_title  imdb_rating  imdb_votes
0              Uri: The Surgical Strike          8.4       35112
11                            Gully Boy          8.2       22440
37                           Article 15          8.3       13417
40                             Super 30          8.2       13972
143                             Tumbbad          8.2       16535
146                           Andhadhun          8.4       51615
325                                Pink          8.2       33902
354                              Dangal          8.4      131338
418                              Masaan          8.1       19904
426                            Drishyam          8.2       58340
436                              Talvar          8.2       26612
469                               Queen          8.2       56406
536                              Haider          8.1       46912
566                                Ugly          8.1       17483
567                                  PK          8.1      143605
589                        Vishwaroopam          8.2       38016
612                  Bhaag Milkha Bhaag          8.2       56205
638                              Shahid          8.3       13537
668                    Paan Singh Tomar          8.2       29994
669                             Kahaani          8.1       53181
693                  Gangs of Wasseypur          8.2       71636
694                  Gangs of Wasseypur          8.2       71636
709                              Barfi!          8.1       70443
714                     OMG: Oh My God!          8.2       46072
778            Zindagi Na Milegi Dobara          8.1       60826
869                               Udaan          8.2       39567
912                            3 Idiots          8.4      310481
930                              Gulaal          8.1       12799
1058                       Black Friday          8.5       16761
1066                     Chak De! India          8.2       68421
1127                   Taare Zameen Par          8.4      148498
1180                  Khosla Ka Ghosla!          8.3       20538
1183               Lage Raho Munna Bhai          8.1       39486
1188                             Omkara          8.1       17594
1195                    Rang De Basanti          8.2      103071
1223                              Black          8.2       31658
1252                              Iqbal          8.1       14864
1384              Swades: We the People          8.2       76737
1403                Munna Bhai M.B.B.S.          8.1       67148
1554         The Legend of Bhagat Singh          8.1       13455
1567  Lagaan: Once Upon a Time in India          8.1       95686
1568  Lagaan: Once Upon a Time in India          8.1       95686
1571                     Dil Chahta Hai          8.1       62313

In [80]:
# Action movies with rating higher than 7

condition1 = movies["genres"].str.split("|").apply(lambda x: 'Action' in x)
movies[(condition1) & (movies["imdb_rating"] > 7.5)][["original_title","imdb_rating","genres"]]

                     original_title  imdb_rating                   genres
0          Uri: The Surgical Strike          8.4         Action|Drama|War
41             Family of Thakurganj          9.4             Action|Drama
84                        Mukkabaaz          8.1       Action|Drama|Sport
106                           Raazi          7.8    Action|Drama|Thriller
110   Parmanu: The Story of Pokhran          7.7     Action|Drama|History
112         Bhavesh Joshi Superhero          7.6             Action|Drama
169                The Ghazi Attack          7.6      Action|Thriller|War
219                       Raag Desh          8.3     Action|Drama|History
258                   Saala Khadoos          7.6       Action|Drama|Sport
280                       Laal Rang          8.0       Action|Crime|Drama
297                     Udta Punjab          7.8       Action|Crime|Drama
354                          Dangal          8.4   Action|Biography|Drama
362               Bajrangi Bhaijaan          8.0      Action|Comedy|Drama
365                            Baby          8.0          Action|Thriller
393      Detective Byomkesh Bakshy!          7.6  Action|Mystery|Thriller
449                           Titli          7.6    Action|Drama|Thriller
536                          Haider          8.1       Action|Crime|Drama
589                    Vishwaroopam          8.2          Action|Thriller
625                     Madras Cafe          7.7    Action|Drama|Thriller
668                Paan Singh Tomar          8.2   Action|Biography|Crime
693              Gangs of Wasseypur          8.2      Action|Comedy|Crime
694              Gangs of Wasseypur          8.2      Action|Comedy|Crime
982                    Jodhaa Akbar          7.6     Action|Drama|History
1039                           1971          7.9         Action|Drama|War
1058                   Black Friday          8.5       Action|Crime|Drama
1188                         Omkara          8.1       Action|Crime|Drama
1293                         Sarkar          7.6       Action|Crime|Drama
1294                          Sehar          7.8       Action|Crime|Drama
1361                        Lakshya          7.9     Action|Drama|Romance
1432                      Gangaajal          7.8       Action|Crime|Drama
1495                        Company          8.0       Action|Crime|Drama
1554     The Legend of Bhagat Singh          8.1   Action|Biography|Drama
1607           Nayak: The Real Hero          7.8    Action|Drama|Thriller

In [81]:
ipl.sample(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
60,1304060,Pune,2022-04-06,2022,14,Mumbai Indians,Kolkata Knight Riders,"Maharashtra Cricket Association Stadium, Pune",Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,5.0,NaN,PJ Cummins,"['RG Sharma', 'Ishan Kishan', 'D Brevis', 'SA ...","['AM Rahane', 'VR Iyer', 'SS Iyer', 'SW Billin...",BNJ Oxenford,KN Ananthapadmanabhan
848,392226,Bloemfontein,2009-05-15,2009,46,Delhi Daredevils,Kings XI Punjab,OUTsurance Oval,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,6.0,NaN,B Lee,"['G Gambhir', 'V Sehwag', 'TM Dilshan', 'AB de...","['S Sohal', 'SM Katich', 'LA Pomersbach', 'Yuv...",HDPK Dharmasena,IL Howell

In [82]:
print(ipl["Team1"].unique())

['Rajasthan Royals' 'Royal Challengers Bangalore' 'Sunrisers Hyderabad'
 'Delhi Capitals' 'Chennai Super Kings' 'Gujarat Titans'
 'Lucknow Super Giants' 'Kolkata Knight Riders' 'Punjab Kings'
 'Mumbai Indians' 'Kings XI Punjab' 'Delhi Daredevils'
 'Rising Pune Supergiant' 'Gujarat Lions' 'Rising Pune Supergiants'
 'Pune Warriors' 'Deccan Chargers' 'Kochi Tuskers Kerala']

In [83]:
# create a function that will take names of 2 ipl teams and return how many matches each won against each other

def team_win_filter(df, team1, team2):
  both_teams = df[
      (
          (df["Team1"] == team1) & (df["Team2"] == team2)
      )
            |
      (
          (df["Team1"] == team2) & (df["Team2"] == team1)
      )
    ]

  return both_teams["WinningTeam"].value_counts()

team1 = "Royal Challengers Bangalore"
team2 = "Chennai Super Kings"

df = team_win_filter(ipl, team1, team2)
df

WinningTeam
Chennai Super Kings            19
Royal Challengers Bangalore    10
Name: count, dtype: int64

### 8) Adding New Columns

In [84]:
movies.sample(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
496,Mastram,tt3431714,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mastram,Mastram,Mastram,0,2013,98,Biography|Drama,4.8,414,How a clerk became an erotica writer.,How a clerk became an erotica writer.,NaN,Rahul Bagga|Tara-Alisha Berry|Aakash Dahiya|Is...,NaN,9 May 2014 (India)
679,Hate Story,tt2309987,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Hate_Story,Hate Story,Hate Story,0,2012,140,Drama|Thriller,5.3,3234,After a powerful businessman has her baby forc...,After a powerful businessman has her baby forc...,Love killed her soul| her body seeks revenge...,Nikhil Dwivedi|Gulshan Devaiah|Paoli Dam|Mohan...,NaN,20 April 2012 (India)

In [85]:
# completely new
movies["Country"] = "India"
movies.sample(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country
1278,My Brother…Nikhil,tt0419992,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/My_Brother..._Ni...,My Brother... Nikhil,My Brother... Nikhil,0,2005,120,Drama|Sport,7.3,1083,The Kapoors have been living in Goa for severa...,Famous swimmer Nikhil Kapoor (Suri) deals with...,NaN,Sanjay Suri|Juhi Chawla|Purab Kohli|Victor Ban...,5 wins & 4 nominations,25 March 2005 (India),India
299,Luv U Alia,tt4581032,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Luv_U_Alia,Luv U Alia,Luv U Alia,0,2015,130,Family|Romance,5.3,77,Can a boy in love win over his beloved's heart...,Can a boy in love win over his beloved's heart...,NaN,V. Ravichandran|Chandan Kumar|Sudeep|P. Ravi S...,NaN,17 September 2015 (India),India

In [86]:
# Column from existing columns
# Create a column 'lead_actor' which will be the first actor from 'actors' column
movies.dropna(inplace=True)
movies["lead_actor"] = movies["actors"].str.split("|").apply(lambda x: x[0])
movies.sample(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country,lead_actor
716,Chittagong (film),tt1785333,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chittagong_(film),Chittagong,Chittagong,0,2012,105,Action|Drama|War,7.2,1334,Set in the turbulence of the 1930s British Ind...,School kids organize an armed revolt in the 19...,Ordinary Boys| Extraordinary Triumph,Manoj Bajpayee|Barry John|Delzad Hiwale|Vega T...,4 wins,12 October 2012 (India),India,Manoj Bajpayee
1332,Deewaar (2004 film),tt0387989,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Deewaar_(2004_film),Deewaar: Let's Bring Our Heroes Home,Deewaar: Let's Bring Our Heroes Home,0,2004,163,Action|Drama|Thriller,6.0,1272,Major Ranvir Kaul (Amitabh Bachchan) is a POW ...,A group of Indian POW (Prisoners Of War) rebel...,Let's bring our heroes home,Amitabh Bachchan|Sanjay Dutt|Akshaye Khanna|Am...,2 nominations,25 June 2004 (India),India,Amitabh Bachchan

### 9) Excess functions

In [87]:
# astype : change dtype of column
# Reduces space held by df if large dataset
print(ipl.info())

print("\n")

ipl["ID"] = ipl["ID"].astype("int32")

print(ipl.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int32(1), object(18)
memory usage: 144.9+ KB
None

In [88]:
ipl = pd.read_csv("/content/ipl-matches.csv")
batsman = pd.read_csv("/content/batsman_runs.csv")
movies = pd.read_csv("/content/movies.csv")
diabetes = pd.read_csv("/content/diabetes.csv")

In [89]:
ipl.sample(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
521,733991,Bangalore,2014-05-09,2014,31,Royal Challengers Bangalore,Kings XI Punjab,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kings XI Punjab,Runs,32.0,NaN,Sandeep Sharma,"['CH Gayle', 'PA Patel', 'V Kohli', 'S Rana', ...","['V Sehwag', 'Mandeep Singh', 'GJ Maxwell', 'D...",S Ravi,K Srinath
704,501269,Mumbai,2011-05-25,2011,Elimination Final,Mumbai Indians,Kolkata Knight Riders,Wankhede Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,4.0,NaN,MM Patel,"['AC Blizzard', 'SR Tendulkar', 'RG Sharma', '...","['G Gambhir', 'JH Kallis', 'SP Goswami', 'MK T...",Asad Rauf,SJA Taufel

In [90]:
movies.sample(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
796,Mere Brother Ki Dulhan,tt1740710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mere_Brother_Ki_...,Mere Brother Ki Dulhan,Mere Brother Ki Dulhan,0,2011,139,Comedy|Family|Romance,5.8,8390,Mere Brother Ki Dulhan is a quirky romantic co...,A quirky rom-com where Kush finds the ideal In...,NaN,Imran Khan|Katrina Kaif|Ali Zafar|Tara D'Souza...,3 nominations,9 September 2011 (USA)
1210,Waris Shah: Ishq Daa Waaris,tt0892113,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Waris_Shah:_Ishq...,Waris Shah: Ishq Daa Waaris,Waris Shah: Ishq Daa Waaris,0,2006,138,Drama|History,7.0,195,When the Mughal emperor Aurangzeb bans music i...,When the Mughal emperor Aurangzeb bans music i...,NaN,Gurdas Maan|Juhi Chawla|Sushant Singh|Divya Du...,NaN,6 October 2006 (UK)

In [91]:
# value_counts
# find out which player has the most potm in finals and semifinals

ipl[(ipl["MatchNumber"] == "Semi Final") | (ipl["MatchNumber"] == "Final")]["Player_of_Match"].value_counts().index[0]

'KA Pollard'

In [92]:
# sort_values

print(movies[["original_title","imdb_rating"]].sort_values("imdb_rating"))
print("\n")
print(movies[["original_title","imdb_rating"]].sort_values("imdb_rating",ascending=False))

               original_title  imdb_rating
298    khel toh ab shuru hoga          0.0
331        Ek Kahani Julie Ki          0.0
407               I Love Desi          0.0
70         Keep Safe Distance          0.0
236   Babuji Ek Ticket Bambai          0.0
...                       ...          ...
58                      Ghost          8.7
1435           Final Solution          8.7
62             Saand Ki Aankh          8.9
1628                 Humsafar          9.0
41       Family of Thakurganj          9.4

[1629 rows x 2 columns]


            original_title  imdb_rating
41    Family of Thakurganj          9.4
1628              Humsafar          9.0
62          Saand Ki Aankh          8.9
1435        Final Solution          8.7
58                   Ghost          8.7
...                    ...          ...
331     Ek Kahani Julie Ki          0.0
407            I Love Desi          0.0
479               Anuradha          0.0
472     Dee Saturday Night          0.0
70      Keep Safe Distance          0.0

[1629 rows x 2 columns]

In [93]:
# unique: only appplicable in Series and not Dataframes

In [94]:
# isna() or isnull() : both givee boolean df of whether is null or not

print(movies.isnull().sum())
print("\n")

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [95]:
# dropna() -> remove nulls
# if any row has atleast 1 null value, it removes the entire row
# removes high amount of data
print(movies.isna().sum())
print("\n")
movies.dropna(inplace=True)
print(movies.isna().sum())

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64


title_x             0
imdb_id             0
poster_path         0
wiki_link           0
title_y             0
original_title      0
is_adult            0
year_of_release     0
runtime             0
genres              0
imdb_rating         0
imdb_votes          0
story               0
summary             0
tagline             0
actors              0
wins_nominations    0
release_date        0
dtype: int64

In [96]:
# fillna -> fills nulls
print(ipl.isna().sum())
print("\n")
ipl = ipl.fillna(0)  # not suggested. Must do column wise filling only
print(ipl.isna().sum())

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64


ID                 0
City               0
Date               0
Season             0
MatchNumber        0
Team1              0
Team2              0
Venue              0
TossWinner         0
TossDecision       0
SuperOver          0
WinningTeam        0
WonBy              0
Margin             0
method             0
Player_of_Match    0
Team1Players       0
Team2Players       0
Umpire1            0
Umpire2            0
dtype: int64

In [97]:
# drop_duplicates
data = {
    "Name": ["Alice", "Bob", "Alice", "Charlie", "Bob"],
    "Age": [24, 27, 24, 22, 27],
    "City": ["Delhi", "Mumbai", "Delhi", "Bangalore", "Mumbai"]
}

df = pd.DataFrame(data)
print(df)
print("\n")

df.drop_duplicates(inplace=True)

print(df)

      Name  Age       City
0    Alice   24      Delhi
1      Bob   27     Mumbai
2    Alice   24      Delhi
3  Charlie   22  Bangalore
4      Bob   27     Mumbai


      Name  Age       City
0    Alice   24      Delhi
1      Bob   27     Mumbai
3  Charlie   22  Bangalore

In [98]:
# drop -> remove particular row/column

data = {
    "Name": ["Alice", "Bob", "Alice", "Charlie", "Bob"],
    "Age": [24, 27, 24, 22, 27],
    "City": ["Delhi", "Mumbai", "Delhi", "Bangalore", "Mumbai"]
}

df = pd.DataFrame(data)
print(df)
print("\n")

# columns
temp = df.drop(columns=["Age"])
print(temp)
print("\n")

# rows
temp = df.drop(index=[0,3])
print(temp)
print('\n')

      Name  Age       City
0    Alice   24      Delhi
1      Bob   27     Mumbai
2    Alice   24      Delhi
3  Charlie   22  Bangalore
4      Bob   27     Mumbai


      Name       City
0    Alice      Delhi
1      Bob     Mumbai
2    Alice      Delhi
3  Charlie  Bangalore
4      Bob     Mumbai


    Name  Age    City
1    Bob   27  Mumbai
2  Alice   24   Delhi
4    Bob   27  Mumbai

In [99]:
ipl = pd.read_csv("/content/ipl-matches.csv")
batsman = pd.read_csv("/content/batsman_runs.csv")
movies = pd.read_csv("/content/imdb-top-1000.csv")
deliveries = pd.read_csv("/content/deliveries.csv")
diabetes = pd.read_csv("/content/diabetes.csv")

In [100]:
movies.sample(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
738,Rockstar,2011,159,Drama,7.7,Imtiaz Ali,Ranbir Kapoor,39501,985912.0,NaN
459,La règle du jeu,1939,110,Comedy,8.0,Jean Renoir,Marcel Dalio,26725,512863371.0,NaN

### GROUP BY

In [103]:
movies.sample(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
325,Bajrangi Bhaijaan,2015,163,Action,8.0,Kabir Khan,Salman Khan,72245,8178001.0,NaN
112,The Sting,1973,129,Comedy,8.3,George Roy Hill,Paul Newman,241513,159600000.0,83.0

In [104]:
genres = movies.groupby("Genre")

In [105]:
# Applying builtin aggregation functions on groupby objects
genres.size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [108]:
genres.size().sort_values(ascending=False)

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Family         2
Fantasy        2
Thriller       1
dtype: int64

In [110]:
genres.first()  # Returns details of first movie that comes in that genre

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [111]:
genres.last()   # Returns details of last movie that comes in that genre

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [115]:
genres.groups   # Returns dictionary of keys: name of genre and values: list of indices of that genre

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [116]:
genres.get_group("Mystery")      # Gives all movies from that genre

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
119,Vertigo,1958,128,Mystery,8.3,Alfred Hitchcock,James Stewart,364368,3200000.0,100.0
145,Shutter Island,2010,138,Mystery,8.2,Martin Scorsese,Leonardo DiCaprio,1129894,128012934.0,63.0
220,Kahaani,2012,122,Mystery,8.1,Sujoy Ghosh,Vidya Balan,57806,1035953.0,NaN
393,Twelve Monkeys,1995,129,Mystery,8.0,Terry Gilliam,Bruce Willis,578443,57141459.0,74.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
714,The Lady Vanishes,1938,96,Mystery,7.8,Alfred Hitchcock,Margaret Lockwood,47400,474203697.0,98.0
829,Spoorloos,1988,107,Mystery,7.7,George Sluizer,Bernard-Pierre Donnadieu,33982,367916835.0,NaN
899,El cuerpo,2012,112,Mystery,7.6,Oriol Paulo,Jose Coronado,57549,140340673.0,NaN
959,Dark City,1998,100,Mystery,7.6,Alex Proyas,Rufus Sewell,187927,14378331.0,66.0
961,Lost Highway,1997,134,Mystery,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0

In [122]:
genres[["IMDB_Rating","No_of_Votes","Gross","Metascore"]].sum()

           IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action          1367.3     72282412  3.263226e+10    10499.0
Adventure        571.5     22576163  9.496922e+09     5020.0
Animation        650.3     21978630  1.463147e+10     6082.0
Biography        698.6     24006844  8.276358e+09     6023.0
Comedy          1224.7     27620327  1.566387e+10     9840.0
Crime            857.8     33533615  8.452632e+09     6706.0
Drama           2299.7     61367304  3.540997e+10    19208.0
Family            15.6       551221  4.391106e+08      158.0
Fantasy           16.0       146222  7.827267e+08        0.0
Film-Noir         23.9       367215  1.259105e+08      287.0
Horror            87.0      3742556  1.034649e+09      880.0
Mystery           95.7      4203004  1.256417e+09      633.0
Thriller           7.8        27733  1.755074e+07       81.0
Western           33.4      1289665  5.822151e+07      313.0

In [123]:
genres[["IMDB_Rating","No_of_Votes","Gross","Metascore"]].mean()

           IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action        7.949419  420246.581395  1.897224e+08  73.419580
Adventure     7.937500  313557.819444  1.319017e+08  78.437500
Animation     7.930488  268032.073171  1.784326e+08  81.093333
Biography     7.938636  272805.045455  9.404952e+07  76.240506
Comedy        7.901290  178195.658065  1.010572e+08  78.720000
Crime         8.016822  313398.271028  7.899656e+07  77.080460
Drama         7.957439  212343.612457  1.225259e+08  79.701245
Family        7.800000  275610.500000  2.195553e+08  79.000000
Fantasy       8.000000   73111.000000  3.913633e+08        NaN
Film-Noir     7.966667  122405.000000  4.197018e+07  95.666667
Horror        7.909091  340232.363636  9.405902e+07  80.000000
Mystery       7.975000  350250.333333  1.047014e+08  79.125000
Thriller      7.800000   27733.000000  1.755074e+07  81.000000
Western       8.350000  322416.250000  1.455538e+07  78.250000

In [129]:
pd.set_option('display.max_columns', None)

In [130]:
deliveries.sample(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
28934,125,2,Chennai Super Kings,Delhi Daredevils,6,6,SK Raina,ML Hayden,PJ Sangwan,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,NaN,NaN,NaN
23566,102,1,Mumbai Indians,Deccan Chargers,4,1,SR Tendulkar,DJ Thornely,RP Singh,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [126]:
deliveries.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [128]:
deliveries[["batsman","batsman_runs"]]

          batsman  batsman_runs
0       DA Warner           0.0
1       DA Warner           0.0
2       DA Warner           4.0
3       DA Warner           0.0
4       DA Warner           0.0
...           ...           ...
72271  MEK Hussey           2.0
72272     M Vijay           2.0
72273     M Vijay           1.0
72274  MEK Hussey           0.0
72275  MEK Hussey           NaN

[72276 rows x 2 columns]

In [135]:
deliveries["batsman"].value_counts()

batsman
SK Raina          1648
G Gambhir         1637
SR Tendulkar      1504
RG Sharma         1491
JH Kallis         1440
                  ...
C Nanda              1
Harmeet Singh        1
YA Abdulla           1
P Parameswaran       1
NJ Rimmington        1
Name: count, Length: 386, dtype: int64

In [136]:
batsman = deliveries.groupby("batsman")

In [145]:
# Top 5 batsman based on batsman runs
batsman["batsman_runs"].sum().sort_values(ascending=False)[:5]

batsman
SK Raina        2255.0
G Gambhir       1973.0
RG Sharma       1875.0
SR Tendulkar    1723.0
MS Dhoni        1693.0
Name: batsman_runs, dtype: float64

In [179]:
# the batsman that hit the highest amount of 6s

highest_6 = deliveries[deliveries["batsman_runs"] == 6][["batsman","batsman_runs"]].groupby("batsman")

highest_6.count().sort_values("batsman_runs",ascending=False).head()

              batsman_runs
batsman
SK Raina                91
CH Gayle                84
AC Gilchrist            82
YK Pathan               82
Yuvraj Singh            75

In [180]:
mask = deliveries["batsman_runs"] == 6
max_6 = deliveries[mask].groupby("batsman")["batsman_runs"]
max_6.count().sort_values(ascending=False).head()

batsman
SK Raina        91
CH Gayle        84
AC Gilchrist    82
YK Pathan       82
Yuvraj Singh    75
Name: batsman_runs, dtype: int64

In [182]:
deliveries.sample(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
52779,223,2,Royal Challengers Bangalore,Rajasthan Royals,8,5,RV Uthappa,KP Pietersen,SR Watson,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,NaN,NaN,NaN
32876,141,2,Delhi Daredevils,Chennai Super Kings,5,3,DA Warner,TM Dilshan,JA Morkel,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,4.0,NaN,NaN,NaN

In [193]:
# find out maximum runs that virat kohli scored against top 3 team
mask = deliveries["batsman"] == "V Kohli"
group = deliveries[mask].groupby("bowling_team")
group["batsman_runs"].sum().sort_values(ascending=False).head(3)

bowling_team
Chennai Super Kings    289.0
Deccan Chargers        255.0
Mumbai Indians         208.0
Name: batsman_runs, dtype: float64

In [194]:
# create a function that takes batsman name as input and find out maximum runs that that batsman scored against top 3 team
def max_runs_against_team(deliveries, name):
  mask = deliveries["batsman"] == name
  group = deliveries[mask].groupby("bowling_team")
  return group["batsman_runs"].sum().sort_values(ascending=False).head(3)

max_runs_against_team(deliveries, "CH Gayle")

bowling_team
Kings XI Punjab     270.0
Mumbai Indians      205.0
Delhi Daredevils    150.0
Name: batsman_runs, dtype: float64