### What is Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

https://pandas.pydata.org/about/index.html

### Pandas Series

A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

In [1]:
import numpy as np
import pandas as pd

### 1) Creating Series

In [2]:
# Series from list of integers
series1 = pd.Series([1,2,3,4,5,6])
print(series1)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
# Series from list of strings
series2 = pd.Series(["Apples", "Oranges", "Kiwi", "Bananas"])
print(series2)

0     Apples
1    Oranges
2       Kiwi
3    Bananas
dtype: object

In [4]:
# Custom indices and names
marks = [10,20,30,40,50]
students = ["A", "B", "C", "D", "E"]
series3 = pd.Series(marks, index=students, name="Student marks")
print(series3)

A    10
B    20
C    30
D    40
E    50
Name: Student marks, dtype: int64

In [5]:
# Series from dictionary
marks = {
    "A": 10,
    "B":20,
    "C":30,
    "D":40,
    "E":50,
}
series = pd.Series(marks)
print(series)

A    10
B    20
C    30
D    40
E    50
dtype: int64

### 2) Series Attributes

In [6]:
marks = {
    "A": 10,
    "B":20,
    "C":30,
    "D":40,
    "E":50,
}
series = pd.Series(marks, name="Marks of Students")
print(series)

series1 = pd.Series([1,2,3,4,5,6])
series2 = pd.Series([1,2,2,4,2,6])
print("\n")
print(series1)
print("\n")
print(series2)

A    10
B    20
C    30
D    40
E    50
Name: Marks of Students, dtype: int64


0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


0    1
1    2
2    2
3    4
4    2
5    6
dtype: int64

In [7]:
# .size : no of elements in series
print(series.size)

5

In [8]:
# .dtype : dtype of elements in series
print(series.dtype)

int64

In [9]:
# .name : name of series
print(series.name)

Marks of Students

In [10]:
# is_unique :  returns true or False whether or not all values are unique
print(series1.is_unique)
print(series2.is_unique)

True
False

In [11]:
# .index : Returns indices of series
print(series.index)
print(series1.index)

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
RangeIndex(start=0, stop=6, step=1)

In [12]:
# .values : Returns values of series
print(series.values)
print(series1.values)

[10 20 30 40 50]
[1 2 3 4 5 6]

### 3) Series Methods

In [13]:
series = pd.Series(np.random.randint(1,100,30))
print(series)

0     29
1     10
2     84
3     82
4     16
5     86
6     96
7     18
8     26
9     42
10    81
11    72
12    42
13    79
14    32
15    32
16    23
17    38
18    92
19     3
20    99
21     7
22    40
23    20
24    17
25    54
26    48
27    51
28    21
29    59
dtype: int64

In [14]:
# head() and tail() : head(n) -> top n rows, tail(n) -> bottom n rows
# if n is not passed, by default, 5 rows are returned
print(series.head())
print("\n")
print(series.head(10))
print("\n")
print(series.tail())
print("\n")
print(series.tail(10))
print("\n")

0    29
1    10
2    84
3    82
4    16
dtype: int64


0    29
1    10
2    84
3    82
4    16
5    86
6    96
7    18
8    26
9    42
dtype: int64


25    54
26    48
27    51
28    21
29    59
dtype: int64


20    99
21     7
22    40
23    20
24    17
25    54
26    48
27    51
28    21
29    59
dtype: int64

In [15]:
# sample(n) -> return random n rows
# if n is not passed, by default, 1 row are returned
print(series.sample())
print("\n")
print(series.sample(10))
print("\n")

17    38
dtype: int64


13    79
6     96
23    20
26    48
29    59
11    72
18    92
8     26
27    51
14    32
dtype: int64

In [16]:
# value_counts() -> returns number of occurances of each value
print(series.value_counts())

42    2
32    2
84    1
29    1
82    1
16    1
96    1
86    1
18    1
26    1
81    1
10    1
72    1
79    1
23    1
38    1
92    1
3     1
99    1
7     1
40    1
20    1
17    1
54    1
48    1
51    1
21    1
59    1
Name: count, dtype: int64

In [17]:
# sort_values() -> sorts series

# Ascending order
print(series.sort_values())
print("\n\n")
# Descending order
print(series.sort_values(ascending=False))

19     3
21     7
1     10
4     16
24    17
7     18
23    20
28    21
16    23
8     26
0     29
15    32
14    32
17    38
22    40
9     42
12    42
26    48
27    51
25    54
29    59
11    72
13    79
10    81
3     82
2     84
5     86
18    92
6     96
20    99
dtype: int64



20    99
6     96
18    92
5     86
2     84
3     82
10    81
13    79
11    72
29    59
25    54
27    51
26    48
9     42
12    42
22    40
17    38
14    32
15    32
0     29
8     26
16    23
28    21
23    20
7     18
24    17
4     16
1     10
21     7
19     3
dtype: int64

In [18]:
# inplace parameter : Modifies original series
series.sort_values(inplace=True)
print(series)

19     3
21     7
1     10
4     16
24    17
7     18
23    20
28    21
16    23
8     26
0     29
15    32
14    32
17    38
22    40
9     42
12    42
26    48
27    51
25    54
29    59
11    72
13    79
10    81
3     82
2     84
5     86
18    92
6     96
20    99
dtype: int64

In [19]:
# sort_index() : sorts indices
# parameters: ascending = True/False , inplace = True/False
series.sort_index(inplace=True)
print(series)

0     29
1     10
2     84
3     82
4     16
5     86
6     96
7     18
8     26
9     42
10    81
11    72
12    42
13    79
14    32
15    32
16    23
17    38
18    92
19     3
20    99
21     7
22    40
23    20
24    17
25    54
26    48
27    51
28    21
29    59
dtype: int64

### 4) Series Math Methods

In [20]:
series = pd.Series(np.random.randint(1,100,10))
print(series)

0    88
1    19
2    68
3    87
4    76
5    37
6    21
7    67
8    60
9    10
dtype: int64

In [21]:
# count : returns number of elements in series
# similar to size but in size, it includes missing values
# but count doesnt

series1 = pd.Series([1,2,4,3,np.nan,8,9,11])

print(series1.count())
print(series1.size)

7
8

In [22]:
# sum() and product() : sum and product of all values
print(series.sum())
print(series.product())

533
23481460333900800

In [23]:
# min() and max()
print(series.max())
print(series.min())

88
10

In [24]:
# statistical methods

print(series.mean())
print(series.median())
print(series.mode())
print(series.std())
print(series.var())

53.3
63.5
0    10
1    19
2    21
3    37
4    60
5    67
6    68
7    76
8    87
9    88
dtype: int64
29.181615216890698
851.5666666666667

In [25]:
# describe() : gives summary of all mathematical functions
print(series.describe())

count    10.000000
mean     53.300000
std      29.181615
min      10.000000
25%      25.000000
50%      63.500000
75%      74.000000
max      88.000000
dtype: float64

### 5) Series Indexing and Slicing

In [26]:
series1 = pd.Series(np.random.randint(1,100,20))
print(series1)

print("\n\n")

series2 = pd.Series(["Apple","Banana","Grape","Plum","Orange","Kiwi","Guava","Watermelon"])
print(series2)

0     44
1     45
2     72
3     65
4      8
5     24
6     36
7     15
8     33
9     47
10    48
11    56
12    83
13    76
14     3
15    20
16    94
17    62
18    42
19    14
dtype: int64



0         Apple
1        Banana
2         Grape
3          Plum
4        Orange
5          Kiwi
6         Guava
7    Watermelon
dtype: object

In [27]:
# Integer indexing
print(series1[0])
print(series2[5])

44
Kiwi

In [28]:
# Slicing
print(series1[0:5])
print("\n")

print(series1[-5:])
print("\n")

print(series1[2::2])
print("\n")

print(series2[0:5])
print("\n")

print(series2[-5:])
print("\n")

0    44
1    45
2    72
3    65
4     8
dtype: int64


15    20
16    94
17    62
18    42
19    14
dtype: int64


2     72
4      8
6     36
8     33
10    48
12    83
14     3
16    94
18    42
dtype: int64


0     Apple
1    Banana
2     Grape
3      Plum
4    Orange
dtype: object


3          Plum
4        Orange
5          Kiwi
6         Guava
7    Watermelon
dtype: object

In [29]:
# Fancy Indexing
print(series1[[1,4,6,9,12]])
print("\n")
print(series2[[1,4,6]])

1     45
4      8
6     36
9     47
12    83
dtype: int64


1    Banana
4    Orange
6     Guava
dtype: object

In [30]:
# Boolean Indexing
print(series1[series1>50])

2     72
3     65
11    56
12    83
13    76
16    94
17    62
dtype: int64

### 6) Excess Functions Series

In [31]:
series = pd.Series([1,1,0,0,1,1,0,1])
series

0    1
1    1
2    0
3    0
4    1
5    1
6    0
7    1
dtype: int64

In [32]:
# astype: changes datatype of series
series = series.astype(bool)
series

0     True
1     True
2    False
3    False
4     True
5     True
6    False
7     True
dtype: bool

In [33]:
# drop_duplicates: removes duplicates from series
series = pd.Series([1,2,3,1,1,3,4,1,3,5,6,1,4,5,9])
series.drop_duplicates()

0     1
1     2
2     3
6     4
9     5
10    6
14    9
dtype: int64

In [34]:
# duplicated: creates a series of bools
# Can be used to find how many duplicates in series
series = pd.Series([1,2,3,1,1,3,4,1,3,5,6,1,4,5,9])
series.duplicated().sum()

np.int64(8)

In [35]:
# isnull : creates a series of bools
# Can be used to find how many nulls in series
series = pd.Series([1,4,np.nan,5,np.nan,1,9,3,np.nan])
series.isna().sum()

np.int64(3)

In [36]:
# dropna : deletes all missing values
print(series)
print("\n")
temp = series.dropna()
print(temp)

0    1.0
1    4.0
2    NaN
3    5.0
4    NaN
5    1.0
6    9.0
7    3.0
8    NaN
dtype: float64


0    1.0
1    4.0
3    5.0
5    1.0
6    9.0
7    3.0
dtype: float64

In [37]:
# fillna : fills all missing values with given values
print(series)
print("\n")
temp = series.fillna("Missing")
print(temp)

0    1.0
1    4.0
2    NaN
3    5.0
4    NaN
5    1.0
6    9.0
7    3.0
8    NaN
dtype: float64


0        1.0
1        4.0
2    Missing
3        5.0
4    Missing
5        1.0
6        9.0
7        3.0
8    Missing
dtype: object

In [38]:
# apply : allows using functions on each row of series
def add(s):
  return s+10

series = pd.Series([1,2,3,4,5,6,7])
print(series.apply(add))

0    11
1    12
2    13
3    14
4    15
5    16
6    17
dtype: int64

# **DataFrame**

In [39]:
# DF from Lists
student_data = [
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,50,2]
]

df = pd.DataFrame(student_data, columns = ["iq","marks","package"])
print(df)

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [40]:
# DF from dictionary
student_dict = {
    'name': ['nitish','ankit','rupesh','rishabh','amit','ankita'],
    'iq': [100,90,120,80,0,0],
    'marks': [80,70,100,50,0,0],
    'package': [10,7,14,2,0,0]
}

df = pd.DataFrame(student_dict)
print(df)

      name   iq  marks  package
0   nitish  100     80       10
1    ankit   90     70        7
2   rupesh  120    100       14
3  rishabh   80     50        2
4     amit    0      0        0
5   ankita    0      0        0

In [41]:
# From CSV
df = pd.read_csv("/content/batsman_runs.csv")
print(df)

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

### 1) DF methods

In [42]:
movies = pd.read_csv("/content/movies.csv")
ipl = pd.read_csv("/content/ipl-matches.csv")
batsman = pd.read_csv("/content/batsman_runs.csv")

In [43]:
# shape
print(movies.shape)
print(ipl.shape)

(1629, 18)
(950, 20)

In [44]:
# dtypes
print(movies.dtypes)
print("\n")
print(ipl.dtypes)

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object


ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [45]:
# index
print(movies.index)
print(ipl.index)

RangeIndex(start=0, stop=1629, step=1)
RangeIndex(start=0, stop=950, step=1)

In [46]:
# columns
print(movies.columns)
print(ipl.columns)
print(batsman.columns)

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')
Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')
Index(['batter', 'batsman_run'], dtype='object')

In [47]:
# values
print(batsman.values)

[['A Ashish Reddy' 280]
 ['A Badoni' 161]
 ['A Chandila' 4]
 ...
 ['Younis Khan' 3]
 ['Yuvraj Singh' 2754]
 ['Z Khan' 117]]

In [48]:
# head and tail
print(movies.head(2))

                    title_x    imdb_id  \
0  Uri: The Surgical Strike  tt8291224
1             Battalion 609  tt9472208

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...
1                                                NaN

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1        https://en.wikipedia.org/wiki/Battalion_609

                    title_y            original_title  is_adult  \
0  Uri: The Surgical Strike  Uri: The Surgical Strike         0
1             Battalion 609             Battalion 609         0

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112
1             2019     131               War          4.1          73

                                               story  \
0  Divided over five chapters  the film chronicle...
1  The story revolves around a cricket match betw...

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN
1  The story of Battalion 609 revolves around a c...     NaN

                                              actors wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...           4 wins
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...              NaN

              release_date
0    11 January 2019 (USA)
1  11 January 2019 (India)

In [49]:
print(ipl.tail(2))

         ID        City        Date   Season MatchNumber  \
948  335983  Chandigarh  2008-04-19  2007/08           2
949  335982   Bangalore  2008-04-18  2007/08           1

                           Team1                  Team2  \
948              Kings XI Punjab    Chennai Super Kings
949  Royal Challengers Bangalore  Kolkata Knight Riders

                                          Venue                   TossWinner  \
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore

    TossDecision SuperOver            WinningTeam WonBy  Margin method  \
948          bat         N    Chennai Super Kings  Runs    33.0    NaN
949        field         N  Kolkata Knight Riders  Runs   140.0    NaN

    Player_of_Match                                       Team1Players  \
948      MEK Hussey  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...
949     BB McCullum  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...

                                          Team2Players    Umpire1      Umpire2
948  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...  MR Benson   SL Shastri
949  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...  Asad Rauf  RE Koertzen

In [50]:
# sample
print(ipl.sample(5))

          ID       City        Date   Season        MatchNumber  \
565   598045  Bangalore  2013-05-14     2013                 63
630   548379  Bangalore  2012-05-23     2012  Elimination Final
229  1178400     Jaipur  2019-04-11     2019                 25
271  1136603     Jaipur  2018-05-11     2018                 43
180  1216516        NaN  2020-10-02  2020/21                 14

                           Team1                Team2  \
565  Royal Challengers Bangalore      Kings XI Punjab
630          Chennai Super Kings       Mumbai Indians
229             Rajasthan Royals  Chennai Super Kings
271          Chennai Super Kings     Rajasthan Royals
180          Sunrisers Hyderabad  Chennai Super Kings

                                   Venue           TossWinner TossDecision  \
565                M Chinnaswamy Stadium      Kings XI Punjab        field
630                M Chinnaswamy Stadium       Mumbai Indians        field
229               Sawai Mansingh Stadium  Chennai Super Kings        field
271               Sawai Mansingh Stadium  Chennai Super Kings          bat
180  Dubai International Cricket Stadium  Sunrisers Hyderabad          bat

    SuperOver          WinningTeam    WonBy  Margin method Player_of_Match  \
565         N      Kings XI Punjab  Wickets     7.0    NaN    AC Gilchrist
630         N  Chennai Super Kings     Runs    38.0    NaN        MS Dhoni
229         N  Chennai Super Kings  Wickets     4.0    NaN        MS Dhoni
271         N     Rajasthan Royals  Wickets     4.0    NaN      JC Buttler
180         N  Sunrisers Hyderabad     Runs     7.0    NaN         PK Garg

                                          Team1Players  \
565  ['CA Pujara', 'CH Gayle', 'V Kohli', 'AB de Vi...
630  ['M Vijay', 'MEK Hussey', 'SK Raina', 'S Badri...
229  ['AM Rahane', 'JC Buttler', 'SV Samson', 'SPD ...
271  ['SR Watson', 'AT Rayudu', 'SK Raina', 'MS Dho...
180  ['DA Warner', 'JM Bairstow', 'MK Pandey', 'KS ...

                                          Team2Players          Umpire1  \
565  ['AC Gilchrist', 'SE Marsh', 'Azhar Mahmood', ...  HDPK Dharmasena
630  ['SR Tendulkar', 'DR Smith', 'RG Sharma', 'KD ...        BF Bowden
229  ['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...     BNJ Oxenford
271  ['JC Buttler', 'BA Stokes', 'AM Rahane', 'SV S...        M Erasmus
180  ['F du Plessis', 'SR Watson', 'AT Rayudu', 'KM...     AK Chaudhary

             Umpire2
565           S Ravi
630  HDPK Dharmasena
229        UV Gandhe
271         YC Barde
180       PR Reiffel

In [51]:
# info
print(movies.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB
None

In [52]:
# describe
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [53]:
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [54]:
# isnull
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [55]:
# duplicated
movies.duplicated().sum()

np.int64(0)

In [56]:
ipl.duplicated().sum()

np.int64(0)

In [57]:
# rename
print(batsman.head())
renamed = batsman.rename(columns={'batter':'batsman','batsman_run':'runs'})
print("\n")
print(renamed.head())

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25


          batsman  runs
0  A Ashish Reddy   280
1        A Badoni   161
2      A Chandila     4
3        A Chopra    53
4     A Choudhary    25

### 2) DF Math Methods

In [58]:
df = pd.DataFrame(np.random.randint(1,100,30).reshape(5,6))
print(df)

    0   1   2   3   4   5
0  14  43  57  38  44  39
1  58   7  74  82  52  52
2  17  47  35  75  10  78
3  29   5  46  82  48  83
4  45  68  58  48  45  96

In [59]:
# sum -> axis argument
print(df.sum(axis=0))   # column wise
print("\n")
print(df.sum(axis=1))  # row wise

0    163
1    170
2    270
3    325
4    199
5    348
dtype: int64


0    235
1    325
2    262
3    293
4    360
dtype: int64

In [60]:
df.mean()

0    32.6
1    34.0
2    54.0
3    65.0
4    39.8
5    69.6
dtype: float64

In [61]:
df.var()

0    350.3
1    744.0
2    212.5
3    424.0
4    287.2
5    548.3
dtype: float64

### 3) Accessing columns from DF

In [62]:
data = {
    0: [10, 20, 30],
    1: [40, 50, 60],
    2: [70, 80, 90]
}

index = ["row_A", "row_B", "row_C"]

df = pd.DataFrame(data, index=index)
print(df)

        0   1   2
row_A  10  40  70
row_B  20  50  80
row_C  30  60  90

In [63]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [24, 27, 22],
    "City": ["Delhi", "Mumbai", "Bangalore"]
}

index = ["id_101", "id_102", "id_103"]

df2 = pd.DataFrame(data, index=index)
print(df2)

           Name  Age       City
id_101    Alice   24      Delhi
id_102      Bob   27     Mumbai
id_103  Charlie   22  Bangalore

In [64]:
# Single column
print(df[0])
print("\n")
print(df2["Name"])

row_A    10
row_B    20
row_C    30
Name: 0, dtype: int64


id_101      Alice
id_102        Bob
id_103    Charlie
Name: Name, dtype: object

In [65]:
# Multiple columns by fancy indexing

print(df[[0,2]])
print("\n")
print(df2[["Name","City","Age"]])

        0   2
row_A  10  70
row_B  20  80
row_C  30  90


           Name       City  Age
id_101    Alice      Delhi   24
id_102      Bob     Mumbai   27
id_103  Charlie  Bangalore   22

### 4) Accessing rows from DF

In [66]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank"],
    "Age": [24, 27, 22, 25, 26, 28],
    "City": ["Delhi", "Mumbai", "Bangalore", "Chennai", "Pune", "Hyderabad"],
    "Salary": [50000, 60000, 55000, 58000, 62000, 65000],
    "Experience": [2, 4, 1, 3, 5, 6]
}

index = [
    "id_101",
    "id_102",
    "id_103",
    "id_104",
    "id_105",
    "id_106"
]

df = pd.DataFrame(data, index=index)
print(df)

           Name  Age       City  Salary  Experience
id_101    Alice   24      Delhi   50000           2
id_102      Bob   27     Mumbai   60000           4
id_103  Charlie   22  Bangalore   55000           1
id_104    David   25    Chennai   58000           3
id_105      Eve   26       Pune   62000           5
id_106    Frank   28  Hyderabad   65000           6

In [67]:
# iloc: Searched used index positions
print(df.iloc[0])   # Single row
print("\n")
print(df.iloc[0:5])  # Multiple rows
print("\n")
print(df.iloc[[0,4,1,3]])  # Fancy indexing

Name          Alice
Age              24
City          Delhi
Salary        50000
Experience        2
Name: id_101, dtype: object


           Name  Age       City  Salary  Experience
id_101    Alice   24      Delhi   50000           2
id_102      Bob   27     Mumbai   60000           4
id_103  Charlie   22  Bangalore   55000           1
id_104    David   25    Chennai   58000           3
id_105      Eve   26       Pune   62000           5


         Name  Age     City  Salary  Experience
id_101  Alice   24    Delhi   50000           2
id_105    Eve   26     Pune   62000           5
id_102    Bob   27   Mumbai   60000           4
id_104  David   25  Chennai   58000           3

In [68]:
# loc : Fetches rows according to index name
print(df.loc["id_101"])   # Single row
print("\n")
print(df.loc["id_101":"id_104"])  # Multiple rows
print("\n")
print(df.loc[["id_101","id_104","id_103"]])  # Fancy indexing

Name          Alice
Age              24
City          Delhi
Salary        50000
Experience        2
Name: id_101, dtype: object


           Name  Age       City  Salary  Experience
id_101    Alice   24      Delhi   50000           2
id_102      Bob   27     Mumbai   60000           4
id_103  Charlie   22  Bangalore   55000           1
id_104    David   25    Chennai   58000           3


           Name  Age       City  Salary  Experience
id_101    Alice   24      Delhi   50000           2
id_104    David   25    Chennai   58000           3
id_103  Charlie   22  Bangalore   55000           1

### 5) Accessing both cols and rows

In [69]:
df

           Name  Age       City  Salary  Experience
id_101    Alice   24      Delhi   50000           2
id_102      Bob   27     Mumbai   60000           4
id_103  Charlie   22  Bangalore   55000           1
id_104    David   25    Chennai   58000           3
id_105      Eve   26       Pune   62000           5
id_106    Frank   28  Hyderabad   65000           6

In [70]:
df.iloc[0:3,0:2]

           Name  Age
id_101    Alice   24
id_102      Bob   27
id_103  Charlie   22

### 6) Applying functions on dataframes

In [71]:
df = pd.DataFrame(np.random.randint(1,100,30).reshape(5,6))
print(df)

    0   1   2   3   4   5
0  21   7  62  93  32  22
1  31  65  14  41  76  85
2   2  38  38   1  27  20
3  73  10  18  61  65  97
4   9  85  10  37   7  67

In [72]:
def add_ten(x):
  return x+10
df = df.apply(add_ten)
df

    0   1   2    3   4    5
0  31  17  72  103  42   32
1  41  75  24   51  86   95
2  12  48  48   11  37   30
3  83  20  28   71  75  107
4  19  95  20   47  17   77

### 7) Filtering DataFrame

In [73]:
ipl.sample(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
349,1082614,Mumbai,2017-04-22,2017,25,Mumbai Indians,Delhi Daredevils,Wankhede Stadium,Delhi Daredevils,field,N,Mumbai Indians,Runs,14.0,NaN,MJ McClenaghan,"['PA Patel', 'JC Buttler', 'N Rana', 'RG Sharm...","['SV Samson', 'AP Tare', 'KK Nair', 'SS Iyer',...",A Nand Kishore,S Ravi
187,1216539,NaN,2020-09-25,2020/21,7,Delhi Capitals,Chennai Super Kings,Dubai International Cricket Stadium,Chennai Super Kings,field,N,Delhi Capitals,Runs,44.0,NaN,PP Shaw,"['PP Shaw', 'S Dhawan', 'RR Pant', 'SS Iyer', ...","['M Vijay', 'SR Watson', 'F du Plessis', 'RD G...",KN Ananthapadmanabhan,RK Illingworth

In [74]:
# find out the final winners
ipl[ipl["MatchNumber"] == "Final"][["Season","WinningTeam"]]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [75]:
# how many super over finishes have occured
ipl[ipl["SuperOver"] == "Y"].shape[0]

14

In [76]:
# how many matches has CSK won in Kolkata
ipl[(ipl["City"] == "Kolkata") & (ipl["WinningTeam"] == "Chennai Super Kings")].shape[0]

5

In [77]:
# toss winner is match winner in percentage
num = ipl[ipl["TossWinner"] == ipl["WinningTeam"]].shape[0]
total_rows = ipl.shape[0]
percentage = (num/total_rows) * 100
print(f"Percentage: {percentage}")

Percentage: 51.473684210526315

In [78]:
movies.sample(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
407,I Love Desi,tt4718678,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/I_Love_Desi,I Love Desi,I Love Desi,0,2015,\N,Comedy|Romance,0.0,0,NaN,Add a Plot »,NaN,Shakti Anand|Arun Bali|Vedant Bali|Sunita Dhir...,NaN,NaN
739,Dhobi Ghat (film),tt1433810,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dhobi_Ghat_(film),Dhobi Ghat,Dhobi Ghat,0,2010,100,Drama,7.0,11792,The lives of 4 different people in the city of...,The lives of four people intersect in Mumbai: ...,NaN,Prateik|Monica Dogra|Kriti Malhotra|Aamir Khan...,1 win & 3 nominations,21 January 2011 (India)

In [79]:
# movies with rating higher than 8 and votes > 10000
movies[(movies["imdb_rating"] > 8) & (movies["imdb_votes"] > 10000)][["original_title","imdb_rating","imdb_votes"]]

                         original_title  imdb_rating  imdb_votes
0              Uri: The Surgical Strike          8.4       35112
11                            Gully Boy          8.2       22440
37                           Article 15          8.3       13417
40                             Super 30          8.2       13972
143                             Tumbbad          8.2       16535
146                           Andhadhun          8.4       51615
325                                Pink          8.2       33902
354                              Dangal          8.4      131338
418                              Masaan          8.1       19904
426                            Drishyam          8.2       58340
436                              Talvar          8.2       26612
469                               Queen          8.2       56406
536                              Haider          8.1       46912
566                                Ugly          8.1       17483
567                                  PK          8.1      143605
589                        Vishwaroopam          8.2       38016
612                  Bhaag Milkha Bhaag          8.2       56205
638                              Shahid          8.3       13537
668                    Paan Singh Tomar          8.2       29994
669                             Kahaani          8.1       53181
693                  Gangs of Wasseypur          8.2       71636
694                  Gangs of Wasseypur          8.2       71636
709                              Barfi!          8.1       70443
714                     OMG: Oh My God!          8.2       46072
778            Zindagi Na Milegi Dobara          8.1       60826
869                               Udaan          8.2       39567
912                            3 Idiots          8.4      310481
930                              Gulaal          8.1       12799
1058                       Black Friday          8.5       16761
1066                     Chak De! India          8.2       68421
1127                   Taare Zameen Par          8.4      148498
1180                  Khosla Ka Ghosla!          8.3       20538
1183               Lage Raho Munna Bhai          8.1       39486
1188                             Omkara          8.1       17594
1195                    Rang De Basanti          8.2      103071
1223                              Black          8.2       31658
1252                              Iqbal          8.1       14864
1384              Swades: We the People          8.2       76737
1403                Munna Bhai M.B.B.S.          8.1       67148
1554         The Legend of Bhagat Singh          8.1       13455
1567  Lagaan: Once Upon a Time in India          8.1       95686
1568  Lagaan: Once Upon a Time in India          8.1       95686
1571                     Dil Chahta Hai          8.1       62313

In [80]:
# Action movies with rating higher than 7

condition1 = movies["genres"].str.split("|").apply(lambda x: 'Action' in x)
movies[(condition1) & (movies["imdb_rating"] > 7.5)][["original_title","imdb_rating","genres"]]

                     original_title  imdb_rating                   genres
0          Uri: The Surgical Strike          8.4         Action|Drama|War
41             Family of Thakurganj          9.4             Action|Drama
84                        Mukkabaaz          8.1       Action|Drama|Sport
106                           Raazi          7.8    Action|Drama|Thriller
110   Parmanu: The Story of Pokhran          7.7     Action|Drama|History
112         Bhavesh Joshi Superhero          7.6             Action|Drama
169                The Ghazi Attack          7.6      Action|Thriller|War
219                       Raag Desh          8.3     Action|Drama|History
258                   Saala Khadoos          7.6       Action|Drama|Sport
280                       Laal Rang          8.0       Action|Crime|Drama
297                     Udta Punjab          7.8       Action|Crime|Drama
354                          Dangal          8.4   Action|Biography|Drama
362               Bajrangi Bhaijaan          8.0      Action|Comedy|Drama
365                            Baby          8.0          Action|Thriller
393      Detective Byomkesh Bakshy!          7.6  Action|Mystery|Thriller
449                           Titli          7.6    Action|Drama|Thriller
536                          Haider          8.1       Action|Crime|Drama
589                    Vishwaroopam          8.2          Action|Thriller
625                     Madras Cafe          7.7    Action|Drama|Thriller
668                Paan Singh Tomar          8.2   Action|Biography|Crime
693              Gangs of Wasseypur          8.2      Action|Comedy|Crime
694              Gangs of Wasseypur          8.2      Action|Comedy|Crime
982                    Jodhaa Akbar          7.6     Action|Drama|History
1039                           1971          7.9         Action|Drama|War
1058                   Black Friday          8.5       Action|Crime|Drama
1188                         Omkara          8.1       Action|Crime|Drama
1293                         Sarkar          7.6       Action|Crime|Drama
1294                          Sehar          7.8       Action|Crime|Drama
1361                        Lakshya          7.9     Action|Drama|Romance
1432                      Gangaajal          7.8       Action|Crime|Drama
1495                        Company          8.0       Action|Crime|Drama
1554     The Legend of Bhagat Singh          8.1   Action|Biography|Drama
1607           Nayak: The Real Hero          7.8    Action|Drama|Thriller

In [81]:
ipl.sample(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
553,598072,Kolkata,2013-05-24,2013,Qualifier 2,Mumbai Indians,Rajasthan Royals,Eden Gardens,Rajasthan Royals,bat,N,Mumbai Indians,Wickets,4.0,NaN,Harbhajan Singh,"['DR Smith', 'AP Tare', 'KD Karthik', 'RG Shar...","['R Dravid', 'AM Rahane', 'SR Watson', 'SV Sam...",C Shamshuddin,SJA Taufel
438,829815,Hyderabad,2015-05-17,2015,56,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,bat,N,Mumbai Indians,Wickets,9.0,NaN,MJ McClenaghan,"['DA Warner', 'S Dhawan', 'MC Henriques', 'EJG...","['LMP Simmons', 'PA Patel', 'RG Sharma', 'AT R...",CB Gaffaney,K Srinath

In [82]:
print(ipl["Team1"].unique())

['Rajasthan Royals' 'Royal Challengers Bangalore' 'Sunrisers Hyderabad'
 'Delhi Capitals' 'Chennai Super Kings' 'Gujarat Titans'
 'Lucknow Super Giants' 'Kolkata Knight Riders' 'Punjab Kings'
 'Mumbai Indians' 'Kings XI Punjab' 'Delhi Daredevils'
 'Rising Pune Supergiant' 'Gujarat Lions' 'Rising Pune Supergiants'
 'Pune Warriors' 'Deccan Chargers' 'Kochi Tuskers Kerala']

In [83]:
# create a function that will take names of 2 ipl teams and return how many matches each won against each other

def team_win_filter(df, team1, team2):
  both_teams = df[
      (
          (df["Team1"] == team1) & (df["Team2"] == team2)
      )
            |
      (
          (df["Team1"] == team2) & (df["Team2"] == team1)
      )
    ]

  return both_teams["WinningTeam"].value_counts()

team1 = "Royal Challengers Bangalore"
team2 = "Chennai Super Kings"

df = team_win_filter(ipl, team1, team2)
df

WinningTeam
Chennai Super Kings            19
Royal Challengers Bangalore    10
Name: count, dtype: int64

### 8) Adding New Columns

In [84]:
movies.sample(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
745,Patiala House (film),tt1535467,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Patiala_House_(f...,Patiala House,Patiala House,0,2011,140,Drama|Sport,5.6,8301,Gurtej Singh Kahlon witnesses his family being...,A victim of British racial violence and profil...,NaN,Rishi Kapoor|Dimple Kapadia|Akshay Kumar|Anush...,NaN,11 February 2011 (India)
1323,Aitraaz,tt0418460,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aitraaz,Aitraaz,Aitraaz,0,2004,160,Drama|Romance|Thriller,6.6,9027,Successful businessman Raj Malhotra (Akshay Ku...,A man is accused of sexual harassment by his f...,play by their rules or...,Akshay Kumar|Kareena Kapoor|Priyanka Chopra|Am...,7 wins & 12 nominations,12 November 2004 (USA)

In [85]:
# completely new
movies["Country"] = "India"
movies.sample(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country
16,Mard Ko Dard Nahi Hota,tt8055888,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mard_Ko_Dard_Nah...,Mard Ko Dard Nahin Hota,Mard Ko Dard Nahin Hota,0,2018,134,Action|Comedy,7.4,3969,It is a story of a young boy Surya who has a r...,It is a story of a young boy Surya who has a r...,NaN,Abhimanyu Dasani|Radhika Madan|Prateek Parmar|...,2 wins & 2 nominations,22 March 2019 (USA),India
915,Wanted (2009 film),tt1084972,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Wanted_(2009_film),Wanted,Wanted,0,2009,147,Action|Thriller,6.6,17321,Mumbai-based middle-classed Jhanvi who lives ...,Radhe is a ruthless gangster who will kill any...,MAFIA WANTS HIM DEAD| POLICE WANTS HIM ALIVE,Salman Khan|Ayesha Takia|Vinod Khanna|Govind N...,1 win & 4 nominations,25 September 2009 (USA),India

In [86]:
# Column from existing columns
# Create a column 'lead_actor' which will be the first actor from 'actors' column
movies.dropna(inplace=True)
movies["lead_actor"] = movies["actors"].str.split("|").apply(lambda x: x[0])
movies.sample(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country,lead_actor
1291,Salaam Namaste,tt0456165,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Salaam_Namaste,Salaam Namaste,Salaam Namaste,0,2005,158,Comedy|Drama|Romance,6.2,6230,Falling in love. It's very easy to do. Being i...,A quirky take on life and relationships as it ...,Let's get to know each other,Saif Ali Khan|Preity Zinta|Arshad Warsi|Javed ...,1 win & 9 nominations,9 September 2005 (India),India,Saif Ali Khan
1285,Morning Raga,tt0419974,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Morning_Raga_(20...,Morning Raga,Morning Raga,0,2004,110,Drama|Music,6.9,290,Morning Raga is about the meeting of worlds. I...,Morning Raga is about the meeting of worlds. I...,A story of three lives. Struck by tragedy. Uni...,Shabana Azmi|Prakash Kovelamudi|Lillete Dubey|...,2 wins & 1 nomination,18 March 2005 (USA),India,Shabana Azmi

### 9) Excess functions

In [87]:
# astype : change dtype of column
# Reduces space held by df if large dataset
print(ipl.info())

print("\n")

ipl["ID"] = ipl["ID"].astype("int32")

print(ipl.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int32(1), object(18)
memory usage: 144.9+ KB
None

In [134]:
ipl = pd.read_csv("/content/ipl-matches.csv")
batsman = pd.read_csv("/content/batsman_runs.csv")
movies = pd.read_csv("/content/movies.csv")
diabetes = pd.read_csv("/content/diabetes.csv")

In [100]:
ipl.sample(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
598,598026,Chennai,2013-04-22,2013,30,Chennai Super Kings,Rajasthan Royals,"MA Chidambaram Stadium, Chepauk",Rajasthan Royals,bat,N,Chennai Super Kings,Wickets,5.0,NaN,MEK Hussey,"['M Vijay', 'MEK Hussey', 'SK Raina', 'MS Dhon...","['SR Watson', 'AM Rahane', 'DH Yagnik', 'R Dra...",S Asnani,AK Chaudhary
771,501201,Delhi,2011-04-10,2011,4,Delhi Daredevils,Mumbai Indians,Feroz Shah Kotla,Delhi Daredevils,bat,N,Mumbai Indians,Wickets,8.0,NaN,SL Malinga,"['DA Warner', 'V Sehwag', 'UBT Chand', 'AJ Fin...","['DJ Jacobs', 'SR Tendulkar', 'AT Rayudu', 'RG...",AM Saheba,RB Tiffin

In [108]:
movies.sample(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
940,Paying Guests,tt1176961,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Paying_Guests,Paying Guests,Paying Guests,0,2009,109,Comedy|Drama,4.2,471,After Bhavesh Parag Parikshat and Jayesh ri...,Four friends' attempts to find employment and ...,NaN,Shreyas Talpade|Javed Jaffrey|Aashish Chaudhar...,NaN,19 June 2009 (India)
1120,Saawariya,tt0758053,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Saawariya,Saawariya,Saawariya,0,2007,142,Drama|Musical|Romance,5.3,6957,Orphaned and homeless Ranbir Raj re-locates to...,Two souls arrive in a small town one on vacat...,Her world was the wait for Love. His| was the ...,Rani Mukerji|Ranbir Kapoor|Sonam Kapoor|Salman...,8 wins & 10 nominations,9 November 2007 (India)

In [107]:
# value_counts
# find out which player has the most potm in finals and semifinals

ipl[(ipl["MatchNumber"] == "Semi Final") | (ipl["MatchNumber"] == "Final")]["Player_of_Match"].value_counts().index[0]

'KA Pollard'

In [113]:
# sort_values

print(movies[["original_title","imdb_rating"]].sort_values("imdb_rating"))
print("\n")
print(movies[["original_title","imdb_rating"]].sort_values("imdb_rating",ascending=False))

               original_title  imdb_rating
298    khel toh ab shuru hoga          0.0
331        Ek Kahani Julie Ki          0.0
407               I Love Desi          0.0
70         Keep Safe Distance          0.0
236   Babuji Ek Ticket Bambai          0.0
...                       ...          ...
58                      Ghost          8.7
1435           Final Solution          8.7
62             Saand Ki Aankh          8.9
1628                 Humsafar          9.0
41       Family of Thakurganj          9.4

[1629 rows x 2 columns]


            original_title  imdb_rating
41    Family of Thakurganj          9.4
1628              Humsafar          9.0
62          Saand Ki Aankh          8.9
1435        Final Solution          8.7
58                   Ghost          8.7
...                    ...          ...
331     Ek Kahani Julie Ki          0.0
407            I Love Desi          0.0
479               Anuradha          0.0
472     Dee Saturday Night          0.0
70      Keep Safe Distance          0.0

[1629 rows x 2 columns]

In [117]:
# unique: only appplicable in Series and not Dataframes

In [135]:
# isna() or isnull() : both givee boolean df of whether is null or not

print(movies.isnull().sum())
print("\n")

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [137]:
# dropna() -> remove nulls
# if any row has atleast 1 null value, it removes the entire row
# removes high amount of data
print(movies.isna().sum())
print("\n")
movies.dropna(inplace=True)
print(movies.isna().sum())

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64


title_x             0
imdb_id             0
poster_path         0
wiki_link           0
title_y             0
original_title      0
is_adult            0
year_of_release     0
runtime             0
genres              0
imdb_rating         0
imdb_votes          0
story               0
summary             0
tagline             0
actors              0
wins_nominations    0
release_date        0
dtype: int64

In [140]:
# fillna -> fills nulls
print(ipl.isna().sum())
print("\n")
ipl = ipl.fillna(0)  # not suggested. Must do column wise filling only
print(ipl.isna().sum())

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64


ID                 0
City               0
Date               0
Season             0
MatchNumber        0
Team1              0
Team2              0
Venue              0
TossWinner         0
TossDecision       0
SuperOver          0
WinningTeam        0
WonBy              0
Margin             0
method             0
Player_of_Match    0
Team1Players       0
Team2Players       0
Umpire1            0
Umpire2            0
dtype: int64

In [142]:
# drop_duplicates
data = {
    "Name": ["Alice", "Bob", "Alice", "Charlie", "Bob"],
    "Age": [24, 27, 24, 22, 27],
    "City": ["Delhi", "Mumbai", "Delhi", "Bangalore", "Mumbai"]
}

df = pd.DataFrame(data)
print(df)
print("\n")

df.drop_duplicates(inplace=True)

print(df)

      Name  Age       City
0    Alice   24      Delhi
1      Bob   27     Mumbai
2    Alice   24      Delhi
3  Charlie   22  Bangalore
4      Bob   27     Mumbai


      Name  Age       City
0    Alice   24      Delhi
1      Bob   27     Mumbai
3  Charlie   22  Bangalore

In [144]:
# drop -> remove particular row/column

data = {
    "Name": ["Alice", "Bob", "Alice", "Charlie", "Bob"],
    "Age": [24, 27, 24, 22, 27],
    "City": ["Delhi", "Mumbai", "Delhi", "Bangalore", "Mumbai"]
}

df = pd.DataFrame(data)
print(df)
print("\n")

# columns
temp = df.drop(columns=["Age"])
print(temp)
print("\n")

# rows
temp = df.drop(index=[0,3])
print(temp)
print('\n')

      Name  Age       City
0    Alice   24      Delhi
1      Bob   27     Mumbai
2    Alice   24      Delhi
3  Charlie   22  Bangalore
4      Bob   27     Mumbai


      Name       City
0    Alice      Delhi
1      Bob     Mumbai
2    Alice      Delhi
3  Charlie  Bangalore
4      Bob     Mumbai


    Name  Age    City
1    Bob   27  Mumbai
2  Alice   24   Delhi
4    Bob   27  Mumbai

In [145]:
ipl = pd.read_csv("/content/ipl-matches.csv")
batsman = pd.read_csv("/content/batsman_runs.csv")
movies = pd.read_csv("/content/imdb-top-1000.csv")
deliveries = pd.read_csv("/content/deliveries.csv")
diabetes = pd.read_csv("/content/diabetes.csv")

In [146]:
movies.sample(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
586,Loving Vincent,2017,94,Animation,7.8,Dorota Kobiela,Hugh Welchman,50778,6735118.0,62.0
804,Abre los ojos,1997,119,Drama,7.7,Alejandro Amenábar,Eduardo Noriega,64082,368234.0,NaN

### GROUP BY

In [147]:
genres = movies.groupby("Genre")

In [150]:
# Applying builtin aggregation functions on groupby objects
genres.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0